export interface IadminPaymentsSp {
      
    "profile": {
        "id": 2129,
        "applicationUserId": "60663c45-dc17-4a98-9019-003586602467",
        "applicationUser": null,
        "companyName": "Gilliam and Johnston Plc",
        "companyRegisterationNumber": "34343461",
        "companyRegisterationNumberFile": "cv.png",
        "licenseNumber": "34634543",
        "licenseFile": "cv.png",
        "bankId": 0,
        "bankAccountNumber": null,
        "iBanNumber": null,
        "companyLogoFile": "cv.png",
        "officePhoneNumber": "354345335",
        "officeMobileNumber": "999999999",
        "websiteLink": "http://www.sample.com",
        "zakatCertificateNumber": 123,
        "zakatCertificateFile": null,
        "saudizationCertificateFile": null,
        "financialStatementFile": null,
        "coCMembershipNumber": 123,
        "coCMembershipFile": null,
        "isoFile": null,
        "companyClassificationId": 0,
        "representativeId": null,
        "districtId": 10200005002,
        "joinRequestStatusId": 2290,
        "companyRegisterationNumberEndDate": "2022-09-15T00:00:00",
        "companyRegisterationNumberStartDate": "2022-09-15T00:00:00",
        "licenseEndDate": "2022-10-01T00:00:00",
        "licenseStartDate": "2022-09-14T00:00:00",
        "vatregistrationCertificateEndDate": "2000-05-01T00:00:00",
        "vatregistrationCertificateStartDate": "2000-05-01T00:00:00",
        "dateCreated": "2022-09-15T17:18:00",
        "projectServiceId": 1,
        "unitNumber": null,
        "shortAddress": null,
        "cityName": null,
        "districtName": null,
        "streetName": "Amir Harrison",
        "buildingNumber": "3453",
        "additionalNumber": "5345",
        "postalCode": "34543",
        "iBanFile": null,
        "professionLicenseFile": null,
        "professionLicenseNumber": "34634543",
        "socialInsuranceCertificateFile": null,
        "socialInsuranceCertificateNumber": null,
        "classificationCertificateFile": null,
        "classificationCertificateNumber": "4444444444",
        "addedValueRegisterationCertificateFile": null,
        "addedValueRegisterationCertificateNumber": null,
        "bankName": null,
        "professionLicenseStartDate": "2022-09-14T00:00:00",
        "professionLicenseEndDate": "2022-10-01T00:00:00",
        "socialInsuranceCertificateStartDate": "2022-09-15T00:00:00",
        "socialInsuranceCertificateEndDate": "2022-09-15T00:00:00",
        "classificationCertificateStartDate": "2000-05-01T00:00:00",
        "classificationCertificateEndDate": "2000-05-01T00:00:00",
        "addedValueRegisterationCertificateStartDate": "0001-01-01T00:00:00",
        "addedValueRegisterationCertificateEndDate": "0001-01-01T00:00:00",
        "zakatCertificateStartDate": null,
        "zakatCertificateEndDate": null,
        "isoNumber": null,
        "isoStartDate": "2022-09-15T00:00:00",
        "isoEndDate": "0001-01-01T00:00:00",
        "financialStatementNumber": null,
        "financialStatementStartDate": "0001-01-01T00:00:00",
        "financialStatementEndDate": "0001-01-01T00:00:00",
        "saudizationCertificateStartDate": "2022-09-15T00:00:00",
        "saudizationCertificateEndDate": "2022-09-15T00:00:00",
        "saudizationCertificateNumber": null,
        "coCMembershipStartDate": null,
        "coCMembershipEndDate": null,
        "projectSubServiceId": 0,
        "accountOverview": null,
        "profilePictureFile": "default.png",
        "bank": null,
        "companyClassification": null,
        "district": null,
        "joinRequestStatus": null,
        "representative": null,
        "employees": [],
        "offers": [
            {
                "id": 50,
                "projectId": 1169,
                "period": "30",
                "cost": 40000.0,
                "numberOfMilestones": 2,
                "contractorCommitments": "string",
                "sizingMethod": "string",
                "contractTerms": "string",
                "disputeResolution": "string",
                "message": "string",
                "dateCreated": "2022-09-11T16:42:00",
                "individualServiceProviderProfileId": null,
                "organizationalServiceProviderProfileId": 2129,
                "isAccepted": true,
                "offerEndDate": "2022-09-30T16:42:00",
                "individualServiceProviderProfile": null,
                "project": null,
                "materials": [],
                "milestones": [],
                "totalCost": 40400.00,
                "negotiations": null
            }
        ],
        "ospprofileSubServices": [],
        "projectService": null,
        "serviceProviderWorks": [],
        "profileAccepted": false,
        "profileCreated": false,
        "profilePicturePath": "https://app.mohandisy.com/files/ProfilePictures/default.png",
        "companyRegisterationNumberPath": "https://app.mohandisy.com/files/OrgServiceProviders/cv.png",
        "licensePath": "https://app.mohandisy.com/files/OrgServiceProviders/cv.png",
        "companyLogoPath": "https://app.mohandisy.com/files/OrgServiceProviders/cv.png",
        "zakatCertificatePath": "https://app.mohandisy.com/files/OrgServiceProviders/",
        "saudizationCertificatePath": "https://app.mohandisy.com/files/OrgServiceProviders/",
        "financialStatementPath": "https://app.mohandisy.com/files/OrgServiceProviders/",
        "coCMembershipPath": "https://app.mohandisy.com/files/OrgServiceProviders/",
        "isoPath": "https://app.mohandisy.com/files/OrgServiceProviders/",
        "professionLicensePath": "https://app.mohandisy.com/files/OrgServiceProviders/",
        "classificationCertificatePath": "https://app.mohandisy.com/files/OrgServiceProviders/",
        "addedValueRegisterationCertificatePath": "https://app.mohandisy.com/files/OrgServiceProviders/"
    },
    "payments": 0.0,
    "paid": 0.0
       
}

export interface IadminPaymentsCients{
      "profile": {
            "id": 2047,
            "applicationUserId": "7d965f54-f925-45e8-a702-7d9dbea8da09",
            "applicationUser": null,
            "firstName": "wessam",
            "lastName": "client",
            "idFile": "cv.png",
            "neighborhood": "1",
            "streetName": "string",
            "buildingNumber": 2665,
            "additionalNumber": 2243,
            "postalCode": "12435",
            "joinRequestStatusId": 2285,
            "districtId": 10200018005,
            "dateCreated": "2022-09-03T17:54:00",
            "idNumber": "1123123123",
            "accountOverview": "newClient",
            "profilePictureFile": "default.png",
            "district": null,
            "joinRequestStatus": null,
            "projects": [
                {
                    "id": 1169,
                    "clientProfileId": 2047,
                    "projectServiceId": 1,
                    "projectSubServiceId": 2,
                    "name": "Jemima Oneill",
                    "projectCategoryId": 3,
                    "projectSubCategoryId": 1042,
                    "districtId": 10500013007,
                    "plotNumber": "246897531",
                    "organizationalChartNumber": "1357982476",
                    "area": 1000.00,
                    "subject": "Fuga Ratione esse o",
                    "code": "20220917001169",
                    "projectRequestStatusId": 3102,
                    "projectRequestStatus": null,
                    "dateCreated": "2022-09-17T13:37:00",
                    "isOpenForOffers": false,
                    "pricequoteEndDate": null,
                    "requiredWorksNotes": "Voluptatem reiciendi",
                    "district": null,
                    "projectCategory": null,
                    "projectService": null,
                    "projectSubCategory": null,
                    "projectSubService": null,
                    "clientProjectDocuments": [],
                    "negotiations": [],
                    "offers": [
                        {
                            "id": 50,
                            "projectId": 1169,
                            "period": "30",
                            "cost": 40000.0,
                            "numberOfMilestones": 2,
                            "contractorCommitments": "string",
                            "sizingMethod": "string",
                            "contractTerms": "string",
                            "disputeResolution": "string",
                            "message": "string",
                            "dateCreated": "2022-09-11T16:42:00",
                            "individualServiceProviderProfileId": null,
                            "organizationalServiceProviderProfileId": 2129,
                            "isAccepted": true,
                            "offerEndDate": "2022-09-30T16:42:00",
                            "individualServiceProviderProfile": null,
                            "organizationalServiceProviderProfile": null,
                            "materials": [],
                            "milestones": [],
                            "totalCost": 40400.00,
                            "negotiations": null
                        }
                    ],
                    "projectComponents": [],
                    "projectRequiredWorks": [],
                    "projectLevels": [],
                    "componentIds": null,
                    "requiredWorkIds": null,
                    "myOffer": null
                }
            ],
            "profilePicturePath": "https://app.mohandisy.com/files/ProfilePictures/default.png",
            "idPath": "https://app.mohandisy.com/files/Clients/cv.png"
        },
        "payments": 0.0,
        "paid": 0.0
    }
